### ISSUE TITLE
Can this respect config.action_mailer.raise_delivery_errors = false

### ISSUE THREAD

**Issue by throttleup** [the-refinery/sparkpost_rails#12]
If a delivery error occurs and this is set to false, a DeliveryException should probably NOT be thrown.

**Comment by dgoerlich** [comment]
That should be pretty easy to implement.  The expected functionality would be, if set to false, to have the delivery handler silently catch and ignore any errors, as described here?

http://www.rubydoc.info/github/mikel/mail/Mail/Message:raise_delivery_errors

**Comment by throttleup** [comment]
Any exception from a delivery method that extends `StandardError` will be caught and ignored or propagated based on raise_delivery_errors by the ActionMailer internals.No need to catch the exception in this gem. The problem is this gem is throwing an Exception. `rescue => e` will only catch decedents of  `StandardError`

https://github.com/mikel/mail/blob/df48a05a7fb5a4271e6df12da7afb26a53494a18/lib/mail/message.rb#L2151

https://robots.thoughtbot.com/rescue-standarderror-not-exception

**Comment by dgoerlich** [comment]
Ah okay.  That's even easier, and your PR makes sense.  Thanks!

**Comment by throttleup** [comment]
Thanks!
