### ISSUE TITLE
No markup in emails / inline_css option

### ISSUE THREAD

**Issue by daniilsunyaev** [the-refinery/sparkpost_rails#16]
Well, as far as I see from docs, `inline_css` is an option for transmission
https://developers.sparkpost.com/api/#/reference/transmissions
and it appear to be false by default.
Now, when I use sparkpost_rails to send email with template saved in the sparkpost account, it looks like the email do not apply inline css styles to elements.
Is it any way to pass `inline_css` to sparkpost via sparkpost_rails? Should it be set somewhere [here](https://github.com/the-refinery/sparkpost_rails/blob/master/lib/sparkpost_rails/delivery_method.rb#L188-L200)?

**Comment by daniilsunyaev** [comment]
https://github.com/the-refinery/sparkpost_rails/pull/18

**Comment by dgoerlich** [comment]
Thanks! I've just merged it in, and I'm going to be cutting a new version of the gem here in the next day or two.
