### ISSUE TITLE
ActionMailer still looking for ActionView mailer templates

### ISSUE THREAD

**Issue by bosunolanrewaju** [the-refinery/sparkpost_rails#21]
I am not sure what setup I have missed. But for some reasons running the code below (sending `template_id` with `sparkpost_data`) gives `ActionView::MissingTemplate Error`

```
data = {
  template_id: 'my-template',
  substitution_data: 
    first_name: user.first_name
  }
}
mail(to: 'user-email@example.com', sparkpost_data: data)
```
I have
`config.action_mailer.delivery_method = :sparkpost` in the application environment configuration file
'SPARKPOST_API_KEY' set in environment variables and this in `initializers/sparkposts_rails.rb`
```
SparkPostRails.configure do |c|
  c.transactional = true
end
```

**Comment by dgoerlich** [comment]
Oh yeah - that's a good point.  ActionMailer, by default, is going to attempt to render the associated view(s).  That's not something we can work around in the gem, but we should probably update the readme to document this.  Probably the easiest way will be to explicitly pass in an empty text part:

```
mail(to: 'user-email@example.com', sparkpost_data: data) do |format|
    format.text {render text: ""}
end
```

Something like that should get you up and running.

**Comment by bosunolanrewaju** [comment]
Thanks for your response. I resorted to using `ruby_sparkpost` gem from Sparkpost. Though, it works fine, just difficult to test because it doesn't use ActionMailer. This is the reason for trying to make this gem work since I can test email delivery and its content with capybara_email. Thanks

**Comment by bosunolanrewaju** [comment]
@dgoerlich thanks it worked. I didn't know the mail function from ActionMailer takes a block that you can define the template and layout in.
