### ISSUE TITLE
Release official gem?

### ISSUE THREAD

**Issue by sman591** [the-refinery/sparkpost_rails#3]
Is there a reason this isn't on RubyGems?

**Comment by kevinkimball** [comment]
It was a hackathon project, and isn't tested or very good at all really. It is not official. I would not suggest using it in a production environment, and it is not supported.

**Comment by sman591** [comment]
What big issues are you seeing? I haven't tried this yet, but I'm looking to integrate Sparkpost as the mailer, and this gem conceptually does exactly what I need, and I'm happy to finish it up to get it to a relatively production ready level.

**Comment by kevinkimball** [comment]
I honestly haven't looked at it in a year. I would imagine it has a number of issues. Biggest one would be no tests or missing functionality. 

They have an API gem here https://github.com/SparkPost/ruby-sparkpost/blob/master/README.md and I would suggest putting that in your mailer class.

**Comment by kevinkimball** [comment]
@sman591 it looks like @dgoerlich is going to take over development of this, add some tests, and get an a RubyGems release out, so your hopes may yet be answered :wink:

**Comment by sman591** [comment]
Awesome! I'll keep an eye out

**Comment by dgoerlich** [comment]
@kevinkimball  has been gracious enough to allow The Refinery to pick up ongoing development on this gem.  We are compiling the list of things we need and want to add / enhance / improve, and identifying the mission critical ones to getting it to a production-ready 1.0.0 release.  Kevin put together an excellent start, and we are excited to take the hand-off and keep running with it.

**Comment by dgoerlich** [comment]
It's official!  A version 1.0.1 is on RubyGems, complete with a test suite too.  

https://rubygems.org/gems/sparkpost_rails
