### ISSUE TITLE
:recipient_list_id instead of :list_id

### ISSUE THREAD

**Issue by Shoroh** [the-refinery/sparkpost_rails#37]
Hi guys! 
First of all thank you for the gem, it's awesome!

There is a little mistake in manual for the gem. As I see you use sparkpost_data[:recipient_list_id] as a pointer to SparkPost recipient list. But in manual you recommend to use :list_id — https://github.com/the-refinery/sparkpost_rails#recipient-lists

Could you please fix this topic?

**Comment by AlexanderMint** [comment]
Thanks. list_id doesn't work

**Comment by dgoerlich** [comment]
Thanks!  Fixed! :)
