### ISSUE TITLE
Potential Problem with CC: ActionMailer Parameter

### ISSUE THREAD

**Issue by DaveX101** [the-refinery/sparkpost_rails#46]
Hi, I am using sparkpost_rails 1.4.0 with rails 4.2.8 

When I try to include an Ruby Array of Emails for the "cc" parameter for  Action Mailer, I receive this error from SparkPost during delivery:

```
{"message"=>"invalid data format/type", "description"=>"content.headers json dictionary value has type 'json_array' when expecting type 'string'", "code"=>"1300"}
```

However, when I use the same exact array for a "bcc" parameter, the mail successfully goes through and the BCC work as I would expect. 

Could there be a problem in how these headers are constructed? 

Thanks in advance.

**Comment by jplethier** [comment]
Any news about this issue? I am having the same problem here using the recipient_interceptor gem, because it puts a empty array on CC parameter for mail message.

**Comment by aalfson** [comment]
I've got the same issue. Bcc works, but cc doesn't
