### ISSUE TITLE
Turn off Sparkpost SMTP dynamically

### ISSUE THREAD

**Issue by ManuelFrigerio** [the-refinery/sparkpost_rails#49]
Hi,

Is it possible to turn off this gem on the fly? In my case, I want people to use their own SMTP settings but when I try emails are still sent through SparkPost.

Thanks

**Comment by dgoerlich** [comment]
Actually, I think this might be how to accomplish this:

https://stackoverflow.com/questions/6572344/switch-mail-delivery-method-in-rails-during-runtime?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
