### ISSUE TITLE
Rails >= 6.0.0.rc2 Support

### ISSUE THREAD

**Issue by chmatos** [the-refinery/sparkpost_rails#66]

**Comment by brandoncc** [comment]
Rails 6 is officially out, is compatibility planned?

**Comment by olliebennett** [comment]
Since [v 1.5.2](https://github.com/the-refinery/sparkpost_rails/blob/master/CHANGELOG.md#152) it seems Rails 6 is now supported! :+1: Close this issue?

**Comment by chmatos** [comment]
Yes, pls, close this issue.
When I opened there was not have 1.5.2.
Tks a lot.

Em qua, 2 de out de 2019 às 11:59, Ollie Bennett <notifications@github.com>
escreveu:
