### ISSUE TITLE
Attachment B64 Wrapping

### ISSUE THREAD

**Issue by yepher** [the-refinery/sparkpost_rails#7]
Great library and thanks for sharing. 

## Minor Issue

I've heard some speculation that ` Base64.encode64` might add `\r\n` on some platforms in which case this code may not be sufficient:

https://github.com/the-refinery/sparkpost_rails/blob/master/lib/sparkpost_rails/delivery_method.rb#L167

But while looking at this I found `Base64.strict_encode64` which maybe a better overall solution.

## References

* [StackOverflow](http://stackoverflow.com/questions/2620975/strange-n-in-base64-encoded-string-in-ruby/4680044#4680044)
* [Docs](http://ruby-doc.org/stdlib-2.2.0/libdoc/base64/rdoc/Base64.html#method-i-strict_decode64)

**Comment by dgoerlich** [comment]
Great catch! A very easy change to make, and is absolutely the better way to do this.  It's added to the v1.2.0 branch.  Thanks!
